### ISSUE TITLE
Error With "Import distro"

### ISSUE THREAD

**Issue by DarkReitor** [twelvesec/rootend#7]
![image](https://user-images.githubusercontent.com/45410348/87624049-5e9ab480-c6ec-11ea-96b2-1e5bf48fde6e.png)

**Comment by nickvourd** [comment]
Did you use python3?

**Comment by DarkReitor** [comment]
> Did you use python3?

Yes I did

**Comment by nickvourd** [comment]
Distro is a default module in python 3.8, our tool tested on Ubuntu 20, Debian 11, Centos 8, arch etc and works fine.

 https://distro.readthedocs.io/en/latest/
